name: Merge Freeze Labeler

on:
  pull_request:
    types: [opened, closed, reopened, synchronize]
    branches:
      - "release/*"

jobs:
  update-merge-freeze-label:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Manage merge-freeze label on all open PRs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # 取得所有 open PR
          prs=$(gh pr list --state open --json number --jq '.[] | .number')

          # 判斷事件型態
          if [[ "${{ github.event.action }}" == "opened" || "${{ github.event.action }}" == "reopened" || "${{ github.event.action }}" == "synchronize" ]]; then
            # PR open/reopen/sync 時，加上 merge-freeze label
            for pr in $prs; do
              gh pr edit $pr --add-label merge-freeze || true
            done
          elif [[ "${{ github.event.action }}" == "closed" ]]; then
            # PR close/merge 時，移除 merge-freeze label
            for pr in $prs; do
              gh pr edit $pr --remove-label merge-freeze || true
            done
          fi
        # 註解：這段腳本會根據 PR 事件型態，對所有 open PR 加上或移除 merge-freeze label
